### ISSUE TITLE
Need to update Wiki, mising Disable CR translation to CRLF command and arguments. 

### ISSUE THREAD

**Issue by m0jek** [taylorza/zxn-wifiprn#3]
Hi,

I am not sure if I can do a PR for the Wiki, so I am raising an issue instead. 
Basically the section "Driver Commands" is missing the actual commands to disable/enable CR translation . Probabaly just an oversight :)

Something like the below?

# Driver Commands
|CMD ID|Command|Arguments|Example|
|------|-------|---------|-------|
| 1 |Set Max Line Length |Max Line Length|`DRIVER 80, 1, 32`<br>80 Driver ID for the printer driver<br>1 Command ID to set the max line length<br>32 The desired line length |
| 2 |CR translation to CRLF| State | Disable the CR translation<br>`DRIVER 80, 2, 0`<br>Enable CR translation (default)<br>`DRIVER 80, 2, 1`

**Comment by taylorza** [comment]
Fixed, thank you!
